~Adicionando documentação aos métodos HTTP.
Rocketseat/bootcamp-gostack-desafio-01 pull request #4
Opened 2019-10-15 03:17 UTC by GitArika

Levei em consideração a forma como Diego anota as propriedades Http durante o módulo de Ambiente e conceitos.

2019-10-15 23:25 UTC, pedroSoaresll commented on index.js
> + */
experimenta JsDoc

https://devdocs.io/jsdoc/

2019-10-15 23:25 UTC, pedroSoaresll commented on index.js
> + */
experimenta JsDoc

https://devdocs.io/jsdoc/

2019-10-15 23:25 UTC, pedroSoaresll commented on index.js
> + */
experimenta JsDoc

https://devdocs.io/jsdoc/

2019-10-15 23:25 UTC, pedroSoaresll commented on index.js
> + * Adiciona uma nova tarefa no projeto escolhido via id;
experimenta JsDoc

https://devdocs.io/jsdoc/

2019-10-18 12:06 UTC, jpedroschmitz requested changes

2019-10-18 12:06 UTC, jpedroschmitz commented on index.js
> + * Deleta o projeto associado ao id presente nos parametros da rota.
Teria como ajeitar a acentuação da palavra `parâmetros`?

2019-10-18 12:06 UTC, jpedroschmitz commented on index.js
> + * Altera o titulo do projeto com o id presente nos parametros da rota.
Acredito que você colocou um `t` a mais no `title`. Além disso é preciso ajeitar a acentuação da palavra `título` e `parâmetros`.

2019-10-18 12:08 UTC, jpedroschmitz commented
Muito obrigado pela contribuição @GitArika 💜 Eu deixei alguns comentários sobre pequenas melhorias. Se puder ajeitar isso antes de eu fazer o merge eu ficaria muito agradecido!

Keep rocking 🚀

2019-10-18 12:33 UTC, GitArika commented on index.js
> + * Deleta o projeto associado ao id presente nos parametros da rota.
Sim, irei mandar um pull request ainda hoje refinando o máximo possível!

2019-10-18 12:34 UTC, GitArika commented on index.js
> + * Altera o titulo do projeto com o id presente nos parametros da rota.
Obrigado pelo review! 
Farei a correção e envio o pull request!

2019-10-20 20:28 UTC, GitArika reviewed
Refinado comentários que apresentavam erros.

2019-10-20 21:18 UTC, jpedroschmitz approved these changes

2019-10-20 21:20 UTC, jpedroschmitz commented
Fala @GitArika, muito obrigado pelos ajustes 💜
Keep rocking 🚀

2019-10-20 21:21 UTC, merged